language: node_js
 
branches:
  only:
    - publish_wd
 
env:
  global:
    - URL="https://rawgit.com/w3c/pub-manifest/publish_wd/snapshot/ECHIDNA"
    - DECISION="https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-08-19-pwg#resolution3"
    - secure: "mq6p08iP+OmbvxdBx9xtJGo2nHRMXDkwxxUNUDT8iq3A9c7GmuTOGZAeVExPBPAfHrmgsGy9OceGJ0059UZttMHglTpkmZIXXGJ+xZnWQJGqbYQgpxgcbVfamQXOalxdC6Z2QMvxm965MTxaZTPgzvPMp8L5yLoa64VO9TEGyVd/Yz4pYG1Y+HCOmHiWw7pqfo45jfSyMqqXQ3WpHnIK8Jf2FPtyDvl2PUfPU6HbfvxKSjtAhkhadNR6IEwrtn8dfK1/cMGDHMERbQiL5ZVAqGeMHU9vKc8EbFVGyQgL/e2yuBA0cS4aWMCm2EvreYEy8knJ7P9t3vb/1WLKfNb17vwxbtSja3n4BKH7+OxPb8bQJVDXpc1HdsuGgvopLf2oPe2ZzXiYgfu0Cii00ekS6pSXTvwObcd7hfpfLlBh8hFbarF8iqcICR0p7jhlUyppheFekmH9h12KXT68+gEiuyvN/OyHf2zWu+11OznbRbBZVQncJ+cxjXpE4GxXJvLwpYUzkx2dZGVOuH6WLuHgd0eAfBtCqlIr8UL/ekmBBzhi3u5sJfVBn5rq43nE1QO/WDviuLE09B/Evoz/5EBNb108lPM6Ohdpwi5k0PWO7fJ+yRJSanZnkAIPauOyN0Doajyuz29SWRY0wyeqwjRaCu3wpJg8VvjXBsgk9+nNXyA="
 
script:
  - echo "ok"
 
after_success:
  - test $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
